### ISSUE TITLE
.NET 4.0

### ISSUE THREAD

**Issue by McPhale** [ipvalverde/EPPlus.DataExtractor#4]
Would it be possible to get a version built against .NET 4.0 in nuget?

**Comment by ipvalverde** [comment]
Sure!

**Comment by ipvalverde** [comment]
Fixed with the release of the version 1.3.2

**Comment by McPhale** [comment]
Thanks much!

**Comment by ipvalverde** [comment]
Hi @McPhale 
Sorry about that, the .net 4.0 is no longer supported with this new version. The only one supported now should be the 4.6 since the project uses .netstandard 2.0 ( https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support ).

I'm going to reopen this issue and try to make it compatible at least with the 4.5 again!
Microsoft itself no longer gives support to .net 4.0, I know things are not easy when you're working with legacy system but upgrading to, at least, the supported version would be highly recommended.

**Comment by ipvalverde** [comment]
@McPhale I have pushed the version 2.0.1 with added support to .net 4.0 and 4.5. It should be published in a few hours on nuget, I'll be able to obtain it with `Install-Package EPPlus.DataExtractor -Version 2.0.1`

**Comment by McPhale** [comment]
TY, you're the best!
